services:
  - type: web
    name: bruno-ai-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false # Add your OpenAI API key in the Render dashboard
      - key: DB_URL
        sync: false
      - key: DB_SSL
        value: "true"
      - key: CORS_ORIGIN
        value: "*"
      - key: ALLOW_ALL_ORIGINS
        value: "true"