services:
  - type: web
    name: bruno-ai-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false # Add your OpenAI API key in the Render dashboard
      - key: DB_URL
        sync: false
      - key: DB_SSL
        value: "true"
      - key: CORS_ORIGIN
        value: "*"
      - key: ALLOW_ALL_ORIGINS
        value: "true"
